// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQiq-vVaUiilm_n63LDeMZmQunr8QoIA',
    appId: '1:178102738420:web:0e8560cdac7f0555a0ada1',
    messagingSenderId: '178102738420',
    projectId: 'twinkle-237f4',
    authDomain: 'twinkle-237f4.firebaseapp.com',
    storageBucket: 'twinkle-237f4.firebasestorage.app',
    measurementId: 'G-HY5THDSPF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6H26qi7HKCdpAE3VzkwICx43eBzXdk1o',
    appId: '1:178102738420:android:d2dd31855c210672a0ada1',
    messagingSenderId: '178102738420',
    projectId: 'twinkle-237f4',
    storageBucket: 'twinkle-237f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe_86skyIjyKHKL81roDM4YrrTK07ENWA',
    appId: '1:178102738420:ios:2ff863556c7289b4a0ada1',
    messagingSenderId: '178102738420',
    projectId: 'twinkle-237f4',
    storageBucket: 'twinkle-237f4.firebasestorage.app',
    androidClientId: '178102738420-d86qtvqnlrbk5ttpdetq6tm3jci42om0.apps.googleusercontent.com',
    iosClientId: '178102738420-c27uhoh3rqqnflnc4ak260u75p5ro7fq.apps.googleusercontent.com',
    iosBundleId: 'com.farhan.nextcart',
  );
}
